[package]
name = "linkage_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
thiserror = "1.0"
num-traits = "0.2"
[dependencies.druid]
version = "0.7.0"
